name: Publish to pub.dev

on:
  push:
    tags:
    # use YYYY.MM.VERSION, e.g. 2025.2.1
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
